### PR TITLE
Add violations for Joda Time

### PR DESCRIPTION
**Pull request by SimenB**
I tried to cover the factories and constructors I reckon are the most commonly used without going over-board

### CODE REVIEW

**Comment by andrewgaul** [comment]
Thank you for your contribution @SimenB!

**Comment by SimenB** [comment]
@andrewgaul Hey, could you do a release of this? We're upgrading to Java 8 next week, would love to have this is :smile:

**Comment by andrewgaul** [comment]
@SimenB 1.4.0 released and synced to Maven Central.

**Comment by SimenB** [comment]
Great, thanks!

**Pull request merged**
