### PR TITLE
Allow multiple violation files, including classpath references. Fixes #22 and #42.

### LINKED ISSUE #22: Allow multiple violations files
This will allow users to migrate between different libraries, e.g., Apache Commons to Google Guava.  Continuing on from discussion in #21.

### LINKED ISSUE #42: violations file should be loadable from class path
Most other plugins that need a resource (e.g. checkstyle, pmd, findbugs etc) support loading their resource file from the classpath. This allows packaging up all these policy files into a convenient jar and adding it as a dependency to the plugin(s). 

Modernizer only loads its internal file from the classpath and any user defined file is loaded with an explicit `new File(...)`. It should be possible to load user defined files from the class path.

### PR DESCRIPTION
**Pull request by ArturGajowy**
We need this in https://github.com/prestodb/presto/pull/7204. Otherwise we'd have to copy the original violations xml into our project, which we'd like to avoid :)

### CODE REVIEW

**Comment by ArturGajowy** [comment]
This will fix #42

**Comment by ankon** [comment]
Why the maven wrapper commit? Wouldn't that better fit into a separate PR?

**Comment by ArturGajowy** [comment]
@ankon The wrapper was needed by me to do the changes. If you guys don't want the wrapper, just drop that commit / tell me and I'll do it :)

**Comment by andrewgaul** [comment]
I merged the bulk of the functionality as f8a3824794e9a97d0f581422462a1576f91b4635, cda3b1bae5b2820b2aa70f374316155aadca475e, 978b18ee36e41148bf4fcaccdae12efc48cbf108, 995cbd0a2c78e11491f15d439ecb417142184d2f, and c90cd96e1d5496713dc6165c5ff17bc0c3bfa659.  I do not understand the maven wrapper so I did not merge that.  Thank you for your contribution @ArturGajowy!

**Pull request closed without merging**
